# Generated by Django 4.2.6 on 2023-10-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0002_contactus_helpandsupport'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(upload_to='profile-photos/')),
            ],
        ),
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='Contact',
        ),
    ]
